{{alias}}
proxy = +forward-override{forward-socks5 localhost:55777 .}

{proxy}
.soulogic.com
.youtube.com
.googlevideo.com
.ytimg.com
.facebook.com
.imgur.com
.twitter.com
.blogspot.com
.jp
.fbcdn.net
.appspot.com
.chinagfw.org
.blogger.com
.googleapis.com
.googleusercontent.com
.mail.google.com
.xys.org
.nytimes.com
.img.ly
.fc2.com
.thepiratebay.org
.thepiratebay.se
.bit.ly
.dropbox.com
.gstatic.com
.t.co
.youtu.be
.plus.google.com
.feedproxy.google.com
.feeds.feedburner.com
.feedburner.google.com
.drive.google.com
.picasaweb.google.com
.wordpress.com
.wp.me
.wpcomwidgets.com
.player.vimeo.com
.slideshare.net
.calameo.com
.mitbbs.com
.fc2.com
.pornhub.com
.eyny.com
